/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-sso
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AcceptedTermsVersionData } from './AcceptedTermsVersionData';
import {
    AcceptedTermsVersionDataFromJSON,
    AcceptedTermsVersionDataFromJSONTyped,
    AcceptedTermsVersionDataToJSON,
} from './AcceptedTermsVersionData';

/**
 * 
 * @export
 * @interface AcceptedTermsVersionResponse
 */
export interface AcceptedTermsVersionResponse {
    /**
     * 
     * @type {AcceptedTermsVersionData}
     * @memberof AcceptedTermsVersionResponse
     */
    acceptedTermsVersion: AcceptedTermsVersionData;
    /**
     * 
     * @type {string}
     * @memberof AcceptedTermsVersionResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof AcceptedTermsVersionResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the AcceptedTermsVersionResponse interface.
 */
export function instanceOfAcceptedTermsVersionResponse(value: object): value is AcceptedTermsVersionResponse {
    if (!('acceptedTermsVersion' in value) || value['acceptedTermsVersion'] === undefined) return false;
    return true;
}

export function AcceptedTermsVersionResponseFromJSON(json: any): AcceptedTermsVersionResponse {
    return AcceptedTermsVersionResponseFromJSONTyped(json, false);
}

export function AcceptedTermsVersionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptedTermsVersionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'acceptedTermsVersion': AcceptedTermsVersionDataFromJSON(json['acceptedTermsVersion']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function AcceptedTermsVersionResponseToJSON(value?: AcceptedTermsVersionResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'acceptedTermsVersion': AcceptedTermsVersionDataToJSON(value['acceptedTermsVersion']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

