/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-sso
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckReturnRouteResponse
 */
export interface CheckReturnRouteResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CheckReturnRouteResponse
     */
    valid: boolean;
}

/**
 * Check if a given object implements the CheckReturnRouteResponse interface.
 */
export function instanceOfCheckReturnRouteResponse(value: object): value is CheckReturnRouteResponse {
    if (!('valid' in value) || value['valid'] === undefined) return false;
    return true;
}

export function CheckReturnRouteResponseFromJSON(json: any): CheckReturnRouteResponse {
    return CheckReturnRouteResponseFromJSONTyped(json, false);
}

export function CheckReturnRouteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckReturnRouteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'valid': json['valid'],
    };
}

export function CheckReturnRouteResponseToJSON(value?: CheckReturnRouteResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'valid': value['valid'],
    };
}

