/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-sso
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OauthServiceSubscriptionData
 */
export interface OauthServiceSubscriptionData {
    /**
     * 
     * @type {number}
     * @memberof OauthServiceSubscriptionData
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof OauthServiceSubscriptionData
     */
    oauthServiceId: number;
    /**
     * 
     * @type {string}
     * @memberof OauthServiceSubscriptionData
     */
    model: string;
    /**
     * 
     * @type {boolean}
     * @memberof OauthServiceSubscriptionData
     */
    creation: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OauthServiceSubscriptionData
     */
    updates: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OauthServiceSubscriptionData
     */
    deletion: boolean;
}

/**
 * Check if a given object implements the OauthServiceSubscriptionData interface.
 */
export function instanceOfOauthServiceSubscriptionData(value: object): value is OauthServiceSubscriptionData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('oauthServiceId' in value) || value['oauthServiceId'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('creation' in value) || value['creation'] === undefined) return false;
    if (!('updates' in value) || value['updates'] === undefined) return false;
    if (!('deletion' in value) || value['deletion'] === undefined) return false;
    return true;
}

export function OauthServiceSubscriptionDataFromJSON(json: any): OauthServiceSubscriptionData {
    return OauthServiceSubscriptionDataFromJSONTyped(json, false);
}

export function OauthServiceSubscriptionDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): OauthServiceSubscriptionData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'oauthServiceId': json['oauthServiceId'],
        'model': json['model'],
        'creation': json['creation'],
        'updates': json['updates'],
        'deletion': json['deletion'],
    };
}

export function OauthServiceSubscriptionDataToJSON(value?: OauthServiceSubscriptionData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'oauthServiceId': value['oauthServiceId'],
        'model': value['model'],
        'creation': value['creation'],
        'updates': value['updates'],
        'deletion': value['deletion'],
    };
}

