/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-sso
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OauthServiceSubscriptionsMeta
 */
export interface OauthServiceSubscriptionsMeta {
    /**
     * 
     * @type {string}
     * @memberof OauthServiceSubscriptionsMeta
     */
    service?: string;
    /**
     * 
     * @type {string}
     * @memberof OauthServiceSubscriptionsMeta
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof OauthServiceSubscriptionsMeta
     */
    sort?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OauthServiceSubscriptionsMeta
     */
    ascending?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OauthServiceSubscriptionsMeta
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof OauthServiceSubscriptionsMeta
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof OauthServiceSubscriptionsMeta
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the OauthServiceSubscriptionsMeta interface.
 */
export function instanceOfOauthServiceSubscriptionsMeta(value: object): value is OauthServiceSubscriptionsMeta {
    return true;
}

export function OauthServiceSubscriptionsMetaFromJSON(json: any): OauthServiceSubscriptionsMeta {
    return OauthServiceSubscriptionsMetaFromJSONTyped(json, false);
}

export function OauthServiceSubscriptionsMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): OauthServiceSubscriptionsMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'] == null ? undefined : json['service'],
        'model': json['model'] == null ? undefined : json['model'],
        'sort': json['sort'] == null ? undefined : json['sort'],
        'ascending': json['ascending'] == null ? undefined : json['ascending'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function OauthServiceSubscriptionsMetaToJSON(value?: OauthServiceSubscriptionsMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'service': value['service'],
        'model': value['model'],
        'sort': value['sort'],
        'ascending': value['ascending'],
        'limit': value['limit'],
        'offset': value['offset'],
        'totalCount': value['totalCount'],
    };
}

