/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-sso
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OauthServiceSubscriptionData } from './OauthServiceSubscriptionData';
import {
    OauthServiceSubscriptionDataFromJSON,
    OauthServiceSubscriptionDataFromJSONTyped,
    OauthServiceSubscriptionDataToJSON,
} from './OauthServiceSubscriptionData';

/**
 * 
 * @export
 * @interface OauthServiceSubscriptionResponse
 */
export interface OauthServiceSubscriptionResponse {
    /**
     * 
     * @type {OauthServiceSubscriptionData}
     * @memberof OauthServiceSubscriptionResponse
     */
    oauthServiceSubscription: OauthServiceSubscriptionData;
    /**
     * 
     * @type {string}
     * @memberof OauthServiceSubscriptionResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof OauthServiceSubscriptionResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the OauthServiceSubscriptionResponse interface.
 */
export function instanceOfOauthServiceSubscriptionResponse(value: object): value is OauthServiceSubscriptionResponse {
    if (!('oauthServiceSubscription' in value) || value['oauthServiceSubscription'] === undefined) return false;
    return true;
}

export function OauthServiceSubscriptionResponseFromJSON(json: any): OauthServiceSubscriptionResponse {
    return OauthServiceSubscriptionResponseFromJSONTyped(json, false);
}

export function OauthServiceSubscriptionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OauthServiceSubscriptionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'oauthServiceSubscription': OauthServiceSubscriptionDataFromJSON(json['oauthServiceSubscription']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function OauthServiceSubscriptionResponseToJSON(value?: OauthServiceSubscriptionResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'oauthServiceSubscription': OauthServiceSubscriptionDataToJSON(value['oauthServiceSubscription']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

